### ISSUE TITLE
Crashes when used with Malisis mods.

### ISSUE THREAD

**Issue by Drsang** [Flanks255/simplylight#11]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 6/17/20 7:03 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Simply Light (simplylight)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.shadowfacts.forgelin.KotlinAdapter
	at net.minecraftforge.fml.common.FMLModContainer.getLanguageAdapter(FMLModContainer.java:172)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:596)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.shadowfacts.forgelin.KotlinAdapter
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.getLanguageAdapter(FMLModContainer.java:167)
	... 37 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 380117392 bytes (362 MB) / 805306368 bytes (768 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 7 total; -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version               | Source                           | Signature                                |
	|:----- |:--------------- |:--------------------- |:-------------------------------- |:---------------------------------------- |
	| LC    | minecraft       | 1.12.2                | minecraft.jar                    | None                                     |
	| LC    | mcp             | 9.42                  | minecraft.jar                    | None                                     |
	| LC    | FML             | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge           | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | malisiscore     | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar     | None                                     |
	| LC    | malisisblocks   | 1.12.2-6.1.0          | malisisblocks-1.12.2-6.1.0.jar   | None                                     |
	| LC    | malisisdoors    | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar    | None                                     |
	| LC    | malisisswitches | 1.12.2-5.1.0          | malisisswitches-1.12.2-5.1.0.jar | None                                     |
	| LE    | simplylight     | 1.12.2-0.8.7          | simplylight-1.12.2-0.8.7.jar     | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.4.7' Renderer: 'Intel(R) Iris(TM) Graphics 650'

**Comment by Drsang** [comment]
I forget to install the dependencies for 1.12.2 sorry for disturbing.
